### ISSUE TITLE
Htpmovies scrapping not working... it's not giving gdrive link

### ISSUE THREAD

**Issue by spidybro** [missemily22/MultiFunctionBot#11]
![Screenshot_2022-10-27-12-20-49-72_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/89572178/198211735-b2e3657e-077f-48b5-8a4c-9f602b563134.jpg)

**Comment by missemily22** [comment]
@spidybro The script now gives the GPLinks URL
It cannot be further bypassed as GPLinks as further changed its API
