### ISSUE TITLE
Features request 

### ISSUE THREAD

**Issue by MR-JAGANMOHAN** [missemily22/MultiFunctionBot#13]
Need FORCESUB please and also some sites support

And tell me is there any other way to contact you

**Comment by missemily22** [comment]
@MR-JAGANMOHAN ForceSub can be tried
Tell the sites you want support for.
And my Telegram ID is missemily2022.t.me

**Comment by missemily22** [comment]
@MR-JAGANMOHAN ForceSub has been added in latest commit
