### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by pk-628996** [missemily22/MultiFunctionBot#20]
Please add a bypass for https://atglinks.com/

**Comment by missemily22** [comment]
@pk-628996 Share a Sample URL

**Comment by pk-628996** [comment]
> @pk-628996 Share a Sample URL

https://files.technicalatg.com/ECbdddIh

or simply as https://atglinks.com/ECbdddIh

**Comment by missemily22** [comment]
@pk-628996 I am facing Captcha 
And I don't have 2Captcha Key so I cannot bypass that
