### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'from_user'  ; 

### ISSUE THREAD

**Issue by ananth-28** [missemily22/MultiFunctionBot#22]
whats the problem here
![image](https://user-images.githubusercontent.com/106482929/209580941-692d3151-ffe2-4f9e-ada7-96ce2070e74b.png)
please help
hosted on okteto

**Comment by missemily22** [comment]
@missemily22 I tested with the latest build on Koyeb and this error does not come
Did you press anything that lead to this error or its coming from the start?

**Comment by missemily22** [comment]
@ananth-28 
I will probably see all these errors after JEE

So I cannot all these now

**Comment by missemily22** [comment]
@ananth-28 Got the Error
Will try to fix it soon
