### ISSUE TITLE
OKTETO ENDPOINT LINK

### ISSUE THREAD

**Issue by assc0d3r** [missemily22/MultiFunctionBot#23]
6.First copy your app's ENDPOINT as shown in the image and go to Cron-Job.org and sign up!

Can you tell where can I find the link to add in cronjob as there is no image attached.

**Comment by missemily22** [comment]
@assc0d3r Show your Deployment

**Comment by assc0d3r** [comment]
Based on your repo I have deployed tg forward bot on okteto hence I am asking you about endpoint because I am not able to prevent app from sleeping. I would be glad if you can be of help. Thanks in advance.

**Comment by missemily22** [comment]
@assc0d3r Which Repo?
Share Link

**Comment by assc0d3r** [comment]
https://github.com/assc0d3r/tgfwdauto

**Comment by missemily22** [comment]
@assc0d3r Closing due to No Reply!
