### ISSUE TITLE
Bot won't start getting this error

### ISSUE THREAD

**Issue by ED8ET** [missemily22/MultiFunctionBot#29]
![Screenshot_20230118_105211_Chrome Beta](https://user-images.githubusercontent.com/121234233/213083477-ca33ae11-6903-49ad-b3d1-0361052d0908.jpg)

**Comment by missemily22** [comment]
@ED8ET Should have been fixed by now

**Comment by missemily22** [comment]
@ED8ET Fixed in latest commit
